default:
  constant_foi_bi:
    stan_path: "stanmodels/constant_foi_bi.stan"
    rds_path: "stanmodels/ConstantUniformFOI.RDS"
  continuous_foi_normal_bi:
    stan_path: "stanmodels/continuous_foi_normal_bi.stan"
    rds_path: "stanmodels/ContinuousNormalFOI.RDS"
  continuous_foi_normal_log:
    stan_path: "stanmodels/continuous_foi_normal_log.stan"
    rds_path: "stanmodels/ContinuousNormalLogFOI_lowt.RDS"
